blank_issues_enabled: false
contact_links:
  - name: 💬 Community Support
    url: https://discord.gg/KyPfy4Kgb3
    about: Please ask questions and get help from the community here instead of opening a bug report!
